### ISSUE TITLE
draw a couple of maps

### ISSUE THREAD

**Issue by JJPro** [JJPro/tanks-phoenix-react#4]
- [x] Draw a couple of maps. Take a look at this little [demo map](https://github.com/JJPro/tanks-phoenix-react/wiki/Game-World-Sketch) for reference about the element ratios between tanks and other objects. 

- [x] With graph, figure out the coordinates of elements and construct an elixir struct with the following fields: 
`%Map{
     bricks: [%{x: 20, y:200}, ....], 
     steels: [%{x: 20, y:200}, ...], 
  }`

**Comment by Joyce-Zhao** [comment]
map: original
https://docs.google.com/spreadsheets/d/1lC8rDk9rd2Cf5NBBx6x8_NDWYt8OGeCZTcmyTO3OXlo/edit?usp=sharing
map 1
https://docs.google.com/spreadsheets/d/1bEW_OWve15sz_nKI8nrtqSJ8yhTyvlX-4W1Ss5DNGgg/edit?usp=sharing
map 2
https://docs.google.com/spreadsheets/d/1UHrPfLle0OOEktfYZaMecDXXP1LDbpah1mDOSmxMEGs/edit?usp=sharing
map 3
https://docs.google.com/spreadsheets/d/19N7FRryapDLKN5DmX2AhbtA1sRmRetldZ13TPMyCSX8/edit?usp=sharing
map 4
https://docs.google.com/spreadsheets/d/1tbzWHjnBxw6t93sp4aW207y0LVb0ScRJO51bWLw2AR4/edit?usp=sharing

You can take a look at these maps and choose the ones that make sense.

**Comment by Joyce-Zhao** [comment]
map4 -- concentrated version (example)
https://docs.google.com/spreadsheets/d/1HFIwH0-GiSLBVYHxPIoApZhA3QcLe3p_7LIAFxm0LDI/edit?usp=sharing

**Comment by Joyce-Zhao** [comment]
[maps copy.txt](https://github.com/JJPro/tanks-phoenix-react/files/1840074/maps.copy.txt)
