### ISSUE TITLE
game process crash when gameover and both tanks are shooting rapidly

### ISSUE THREAD

**Issue by JJPro** [JJPro/tanks-phoenix-react#9]
# Issue Analysis
This Crash is caused by two client browsers are slightly out of sync for game states. 

The winner's socket will trigger game over and terminate the game process. 
However, the other user is still firing and pushing "fire" event up the socket. But now, the game object is already set to nil by winner's socket. And its attempt to trigger nil.fire crashes the socket process. 

# Possible Solutions
### Solution 1. Delay termination of the game process:
Process.sleep() for a couple of seconds to wait for the other tanks' fire event before terminating the game process. 

### Solution 2. Carefully alternate all game and channel functions to handle the situation where tank could be nil.

**Comment by JJPro** [comment]
@Joyce-Zhao @enjoymrsun

**Comment by enjoymrsun** [comment]
genius

**Comment by Joyce-Zhao** [comment]
great catch

**Comment by JJPro** [comment]
The issue is already solved. Closing the ticket ...
